language: go

sudo: false

cache:
  directories:
    - $HOME/.ccm/repository

matrix:
  fast_finish: true

env:
  global:
    # TODO: why need this?
    - GOMAXPROCS=2
  matrix:
    - CASS=2.2.1
#    - CASS=3.11

go:
  - "1.10"
#  - "1.11"
#  - "tip"

before_install:
  # NOTE: needed for generator test, it generate file like /tmp/092804891/binding.go https://travis-ci.org/pingginp/cqlc/builds/428906675
  - go get github.com/gocql/gocql
  - curl -sSL https://github.com/Masterminds/glide/releases/download/v0.13.1/glide-v0.13.1-linux-amd64.tar.gz | tar -vxz -C ${GOPATH}/bin --strip=1
# FIXME: workaround for gopath
  - mkdir -p ${GOPATH}/src/github.com/relops/cqlc
  - cp -r ./. ${GOPATH}/src/github.com/relops/cqlc
  - cd ${GOPATH}/src/github.com/relops/cqlc

install:
#  - pip install --user PyYAML six
#  - git clone https://github.com/pcmanus/ccm.git
#  - pushd ccm
#  - ./setup.py install --user
#  - popd
  - glide install
  - make install

script:
  - set -e
  - PATH=$PATH:$HOME/.local/bin bash -x integration.sh $CASS
