language: go

sudo: false

cache:
  directories:
    - $HOME/.ccm/repository

matrix:
  fast_finish: true

env:
  global:
    - GOMAXPROCS=2
  matrix:
    - CASS=2.2.13
    - CASS=3.11

go:
  - "1.10"
  - "1.11"
  - "tip"

before_install:
  - curl -sSL https://github.com/Masterminds/glide/releases/download/$GLIDE_VERSION/glide-v0.13.1-linux-amd64.tar.gz | tar -vxz -C /usr/local/bin --strip=1
  - export PATH=$PATH:/home/travis/gopath/bin

install:
  - pip install --user PyYAML six
  - git clone https://github.com/pcmanus/ccm.git
  - pushd ccm
  - ./setup.py install --user
  - popd
  - glide install
  - make install

script:
  - set -e
  - PATH=$PATH:$HOME/.local/bin bash -x integration.sh $CASS
