language: go

sudo: false

cache:
  directories:
    - $HOME/.ccm/repository

matrix:
  fast_finish: true

env:
  global:
    - GOMAXPROCS=2
  matrix:
    - CASS=2.0.6
    - CASS=2.0.7
go:
  - 1.4
  - 1.5

before_install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/relops/csvb
  - go get github.com/cihub/seelog
  #- export PATH=$PATH:/home/travis/gopath/bin:/usr/local/cassandra/bin
  - export PATH=$PATH:/home/travis/gopath/bin

install:
  - pip install --user cql PyYAML six
  - git clone https://github.com/pcmanus/ccm.git
  - pushd ccm
  - ./setup.py install --user
  - popd
  - go get -v ./...

script:
  - set -e
  - PATH=$PATH:$HOME/.local/bin bash -x integration.sh $CASS
